# Generated by Django 4.2.1 on 2023-05-13 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eliments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eliment_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=100)),
                ('eliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elektronica.eliments')),
            ],
        ),
    ]
