# Generated by Django 4.2.1 on 2023-05-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elektronica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eliment_info',
            old_name='value',
            new_name='formula_text',
        ),
        migrations.AlterField(
            model_name='eliment_info',
            name='formula',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
